### ISSUE TITLE
get_duration函数逻辑错误

### ISSUE THREAD

**Issue by ljc545w** [foyoux/pilk#2]
首先感谢作者。我使用您提供的get_duration函数获取silk语音时长，得到了非预期结果，经检查，发现计算frame size的逻辑错误。
建议修改为：`size = size[0] + (size[1] << 8)`

**Comment by lemisky** [comment]
啊，我居然没看到，也不知道我修复没

**Comment by ljc545w** [comment]
> 啊，我居然没看到，也不知道我修复没

看提交作者是修复了的
